[package]
name = "clap-merge-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.99", features = ["full"] }
proc-macro2 = "1.0.94"
quote = "1.0.39"
