[workspace]
resolver = "2"
members = [
    "cli",
    "crates/clap_merge",
    "crates/clap_merge/clap_merge_derive",
    "crates/core",
    "crates/corral", "crates/edge",
    "crates/protocol",
    "crates/resolver", "crates/utils",
    "sidecar",
    "utils",
]
