[package]
name = "kaze"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"

[dependencies.kaze-sidecar]
path = "../crates/kaze-sidecar"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
