[package]
name = "meshcli"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.clap]
version = "4.5.23"
features = ["cargo", "derive"]

[dependencies.rustyline]
version = "15.0.0"
features = ["with-file-history"]
