listen = "0.0.0.0:6081"
threads = 0

[edge]
name = "kaze_shm"
ident = "0.0.0.1"
# sq_bufsize = 65536
# cq_bufsize = 65536
# unlink = true

[log]
directory = "logs"
prefix = "{name}_{ident}"
# rotation = "never"
# suffix = ".log"
# level = "trace"
# max_count = 10

[corral]
# pending_timeout = "1s"
# idle_timeout = "500ms"

#[rate_limit]
# max = 10000 # not present means unlinked
# initial = 0 # 0 means use max
# refill = 0  # 0 means use max
# interval = "100ms"
#
# [[rate_limit.per_msg]]
# ident = "0.0.0.1"
# body_type = "login_req"
# max = 1000
# initial = 0 # 0 means use max
# refill = 0  # 0 means use max
# interval = "100ms"

[local]
# cache_size = "114514"
# live_time = "1s"

pack_bufsize = 65536

[[local.nodes]]
ident = "0.0.0.1"
addr = "127.0.0.1:6081"

[[local.nodes]]
ident = "0.0.0.2"
addr = "127.0.0.1:6082"

[[local.nodes]]
ident = "0.0.0.3"
addr = "127.0.0.1:6083"

# [consul]
# addr = "127.0.0.1:8500"
# consul_token = "consul_token"
# consul_prefix = "sidecar"
# consul_tags = ["kaze"]

# [prometheus]
# listen = "127.0.0.1:9090"
# endpoint = "http://127.0.0.1:9091/metrics"
# interval = "10s"
# username = "username"
# password = "password"
