[package]
name = "kaze-protocol"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = "1.0.95"
prost = "0.13.4"
tokio-util = "0.7.13"
bytes = "1.9.0"
tracing = "0.1.41"

[dependencies.kaze-core]
path = "../core"

[build-dependencies]
prost-build = "0.13.4"
