[package]
name = "clap_merge_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.93", features = ["full"] }
proc-macro2 = "1.0.92"
quote = "1.0.38"
